database:
  user: "getresponse"
  password: "getresponse"
  host: "localhost"
  port: 5432
  dbname: "getresponse"
logger:
  loglevel: "debug"
kafka:
  host: "localhost"
  port: 9092
  producer:
    topic: "getresponse"
    key: "getresponse"